### ISSUE TITLE
build a simple test failed

### ISSUE THREAD

**Issue by xixiaofinland** [surajp/universalmock#15]
I try to stub the Test2.run() function in the test, but it still executes the original production code.
is the stubbing limited to only dependency injected class instances?

**prod code 1**
```
public with sharing class Test1 {
    public Test1() {
    }

    public Integer run() {
        System.debug('Test1.run()');
        Test2 test2 = new Test2();
        Integer r = test2.run2();
        return r;
    }
}

```

**prod code 2**
```
public with sharing class Test2 {
    public Test2() {

    }

    public Integer run2(){
        System.debug('Test2.run2');
        return 2;
    }
}
```

**Test**
```
@IsTest
public with sharing class Test1Test {
    private static final UniversalMocker mockService;
    private static final Test1 sut; // system under test

    static {
        mockService = UniversalMocker.mock(Test2.class);
        sut = new Test1();
    }

    @IsTest
    public static void should_always_return_33() {
        String mockedMethod = 'run2';
        mockService.when(mockedMethod).thenReturn(33);

        Test.startTest();
        Integer size = sut.run();
        Test.stopTest();

        System.assertEquals(33, size);
    }
}

```

**Comment by jlyon87** [comment]
In your test, mock test2, not test1. If test1 is the "sut" then you should be mocking its dependencies, not the class itself that you're testing.

**Comment by xixiaofinland** [comment]
@jlyon87  not sure if I follow you. I'm mocking `test2` by these lines, right?

```
mockService = UniversalMocker.mock(Test2.class);
String mockedMethod = 'run2';
mockService.when(mockedMethod).thenReturn(33);
```

**Comment by surajp** [comment]
@xixiaofinland Yes, you still need to dependency inject and switch out the class at runtime in your test method. Unlike the `HttpCallout` mock class, the stub api merely helps to create a stub. You still have to inject it into your dependent classes yourself. 
In your case, you could use a simple constructor based dependency injection.

```java
public with sharing class Test1 {
   
   private Test2 test2Instance;
    public Test1(Test2 test2Instance) {
         this.test2Instanc= test2Instance;
    }

    public Integer run() {
        System.debug('Test1.run()');
        //Test2 test2 = new Test2();
        Integer r = this.test2Instance.run2();
        return r;
    }
}
``` 
...and in your test method

```java


 @IsTest
    public static void should_always_return_33() {
       
        String mockedMethod = 'run2';
        UniversalMocker mockService = UniversalMocker.mock(Test2.class);
        mockService.when(mockedMethod).thenReturn(33);
        Test2 test2Stub = (Test2) mockService.createStub();
        sut = new Test1(test2Stub);
        Test.startTest();
        Integer size = sut.run();
        Test.stopTest();

        System.assertEquals(33, size);
    }
```

**Comment by xixiaofinland** [comment]
@surajp thanks, now I got the point. I wished it doesn't rely on dependency inject (DI), but still one step closer!
In case the `sut` either invokes multiple functions from various classes one after another OR has a chain of DIs (i.e. classA(ClassB(ClassC) ), I should stub all of them in order to create a pure unit test, am I right?

**Comment by surajp** [comment]
@xixiaofinland great question. Stubbing is most beneficial when you have a platform dependency (SOQL, DML, Custom Permission check, etc.).  For cases where the sut has indirect dependencies on the platform (eg: sut -> layer 2 -> platform api ), you can choose to stub out either the platform dependency or `layer 2`. I suppose a pure unit test would be to stub out `layer 2` , but I'm not really that much of a purist, so I generally stub out only platform dependencies because that's where you reap the most benefit. I still do use DI for all layers because it makes it a lot easier to introduce changes to your code down the line.

**Comment by xixiaofinland** [comment]
Thanks @surajp  for your insight!
