### ISSUE TITLE
Add support for void return methods

### ISSUE THREAD

**Issue by jamessimone** [surajp/universalmock#6]
I added a method to my own implementation:

```java
public UniversalMocker thenReturnVoid() {
    if (!this.isInSetupMode) {
      throw new InvalidOperationException('Invalid order of operations. Must specify method name to mock/assert first');
    }

    this.callCountsMap.put(this.getCurrentKey(), 0);
    this.resetState();
    return this;
}
```
However, you might have some opinion on a better implementation, and I'm all ears!

**Comment by surajp** [comment]
Makes sense to have a dedicated method to return void. What would be some scenarios/reasons where you would want to mock a method to return `void`?

**Comment by jamessimone** [comment]
When I want to validate their inputs - but if this is already possible and I’m misremembering the API, I will gladly close!

**Comment by surajp** [comment]
I see. Yes, you don't have to mock a return value to validate the inputs or call counts after the test. The one scenario I can think of, is when you've overloaded methods. I think adding this to the api makes sense. Will do so. Thanks!

**Comment by surajp** [comment]
Added in #8
